export const ACTIONS = {
  ADD_POSTS: 'ADD_POSTS',
  ADD_POST: 'ADD_POST',
  CLEAN_POST_STATE: 'CLEAN_POST_STATE',
  SEARCH_TEXT: 'SEARCH_TEXT',
  REGISTER_FAILURE: 'REGISTER_FAILURE',
  REGISTER_SUCCESS: 'REGISTER_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
};
